id: A342C3E33
title: 1. Sarvākārajñatācaryā
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:47:53.481316
  last_modified_at: 2022-03-01 21:47:53.481325
