id: A342C3E33
title: 17. Avinivartanīyaliṅgākāra
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:47:53.510278
  last_modified_at: 2022-03-01 21:47:53.510280
