id: A342C3E33
title: 15. Deva
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:47:53.505025
  last_modified_at: 2022-03-01 21:47:53.505029
