id: A342C3E33
title: 24. Abhimāna
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:47:53.540263
  last_modified_at: 2022-03-01 21:47:53.540267
