id: A342C3E33
title: 25. Śikṣā
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:47:53.542936
  last_modified_at: 2022-03-01 21:47:53.542940
